steps:
# Step 1: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image', '-f', 'app/Dockerfile', '.' ]
  id: 'Build Docker Image'

# Step 2: Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image' ]
  id: 'Push Docker Image'

# Step 3: Run unit test    
#install dependencies
- name: 'python:3.8'
  entrypoint: pip
  args: ["install", "-r", "app/requirements.txt", "--user"]
  id: 'Install Dependencies'

# Step 4: Run unit tests
# Run unit tests
- name: 'python:3.8'
  entrypoint: 'python'
  args:
    - '-m'
    - 'unittest'
    - 'discover'
    - '-s'
    - 'app'
    - '-p'
    - 'test_app.py'
  id: 'Run Unit Tests'

# Step 5: Deploy to Cloud Run
- name: google/cloud-sdk
  args: ['gcloud', 'run', 'deploy', 'helloworld-${SHORT_SHA}', 
         '--image=us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image:latest', 
         '--region', 'us-central1', '--platform', 'managed', 
         '--allow-unauthenticated']
         
options:
  logging: CLOUD_LOGGING_ONLY
