steps:
# Step 1: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image', '-f', 'app/Dockerfile', '.' ]
  id: 'Build Docker Image'

# Step 2: Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image' ]
  id: 'Push Docker Image'
  
# Step 3: Run Unit Tests
- name: 'python3'
  args:
    - '-m'
    - 'unittest'
    - 'discover'
    - '-s'
    - '/cicd-project/app'
  id: 'Run Unit Tests'

# Step 4: Deploy to Cloud Run
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Deploy the application to Cloud Run using the correct gcloud command
    gcloud run deploy quickstart-service --image=us-central1-docker.pkg.dev/my-1st-project-417317/cloudrun-repo/quickstart-image:latest --platform managed --region us-central1 --allow-unauthenticated --port=8080 --timeout 10m

options:
  logging: CLOUD_LOGGING_ONLY
